export const SCREENS = {
    LOGIN_SCREEN: 'LOGIN',
    AUTH_SCREEN: "AUTH",
    OTP_SCREEN: "OTP",
    SPLASH_SCREEN: 'SPLASH',
    SIGNUP_SCREEN: "SIGNUP",
    MENU_SCREEN: "MENU",
    DASHBOARD_SCREEN: 'DASHBOARD',
    TRIPS_SCREEN: "TRIPS",
    TRIPS_DETAIL_SCREEN: "TRIPS_DETAILS",
    PICK_UP_SCREEN: 'PICK_UP',
    DROP_OFF_SCREEN:'DROP_OFF'
}

